### ISSUE TITLE
Alpha build fails to launch

### ISSUE THREAD

**Issue by Josh-Star** [matt4682/Shinjiru#1]
Downloaded the win32 alpha build. 
Upon launching Shinjiru.exe I get the error:
`This application failed to start because it could not find or load the Qt platform plugin "windows".`

After a little googling it looks like you might have missed a .dll dependency.

**Comment by matt4682** [comment]
Oh, sorry about that, I forgot that the dependency walker doesn't list the platform plugins, I've updated the zip file with the missing dll, it should work now.

Thanks.

**Comment by Josh-Star** [comment]
Hmm still getting the same error

**Comment by matt4682** [comment]
Woops, the "platform" folder should be named "platforms"

**Comment by Josh-Star** [comment]
Thanks that did it :) Though now when I input my auth code nothing happens, it just says Authorizing at the bottom and the bar doesn't move.

**Comment by matt4682** [comment]
That's really strange, I've been looking into it.

If you relaunch the application it should prompt you for an update, after patching the exe it should give some additional information in a message box about what's going wrong.

Though it'll probably be fixed by reassociating your account with Shinjiru by going into Tools > Settings and clicking the disconnect button and fetching another auth code when the application restarts.

**Comment by Josh-Star** [comment]
Okay thanks, now I get Error: SSL handshake failed.

**Comment by Josh-Star** [comment]
Updated to 0.4, looks to be working now. Thanks, nice work so far :)

**Comment by matt4682** [comment]
Yeah, I just needed to include the SSL dlls and it fixed it all up.

Thanks for testing it out, enjoy :)
